# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VV7g7imboWQcCxw6PLS4RTRWvgz4kqB4
"""

li =[int(i) for i in input("enter a value").split()]

print(li)
li.sort()